package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/zdypro888/iknowledge/internal/engine"
	"github.com/zdypro888/iknowledge/internal/model"
	"github.com/zdypro888/iknowledge/internal/store"
)

// fixture 源码树(impl §10 定案:testdata 不嵌套 .git,测试 setup 复制进
// t.TempDir() 后 git init + git add 再跑全链路)。
var fixture = map[string]string{
	"go.mod":  "module example.com/fixture\n\ngo 1.26\n",
	"main.go": "package main\n\nfunc main() { run() }\n\nfunc run() {}\n",
	"internal/auth/login.go": `package auth

// Login 登录入口;pass 传明文,内部做校验。
func Login(user, pass string) error {
	if user == "" {
		return errEmpty
	}
	return nil
}

var errEmpty error

type Session struct{ ID string }
`,
	"vendor/dep/dep.go":           "package dep\n\nfunc Dep() {}\n",
	"internal/auth/testdata/f.go": "package f\n\nfunc F() {}\n",
	"gen.go":                      "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage main\n\nfunc Gen() {}\n",
}

func setupGitRepo(t *testing.T) string {
	t.Helper()
	t.Setenv("IKNOWLEDGE_STATE_HOME", t.TempDir())
	repo := t.TempDir()
	for rel, content := range fixture {
		p := filepath.Join(repo, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	for _, args := range [][]string{
		{"init", "-q"},
		{"add", "."},
	} {
		cmd := exec.Command("git", append([]string{"-C", repo}, args...)...)
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Skipf("git 不可用,跳过 git 路径 e2e:%v(%s)", err, out)
		}
	}
	return repo
}

func initRepo(t *testing.T, repo string, opts engine.InitOptions) (*engine.Engine, *engine.InitReport) {
	t.Helper()
	s, err := store.Open(repo)
	if err != nil {
		t.Fatal(err)
	}
	e := engine.New(s)
	rep, err := e.Init(opts)
	if err != nil {
		t.Fatalf("Init: %v", err)
	}
	return e, rep
}

// TestE2EGitRepo 全链路(M1.1 段):git 枚举 → 骨架 → 幂等 → 改名迁移历史无损。
func TestE2EGitRepo(t *testing.T) {
	repo := setupGitRepo(t)

	// 未跟踪的新文件(还没 git add)也必须被索引(-co --exclude-standard)。
	if err := os.WriteFile(filepath.Join(repo, "untracked.go"),
		[]byte("package main\n\nfunc Untracked() {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	// gitignore 掉的文件必须排除。
	if err := os.WriteFile(filepath.Join(repo, ".gitignore"), []byte("ignored.go\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(repo, "ignored.go"),
		[]byte("package main\n\nfunc Ignored() {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	e, rep := initRepo(t, repo, engine.InitOptions{})

	// 骨架完整:main.go / login.go / untracked.go;不含 vendor/testdata/生成代码/ignored。
	if rep.Files != 3 {
		t.Errorf("Files = %d, want 3(%s)", rep.Files, rep.Text())
	}
	for _, rel := range []string{"main.go", "internal/auth/login.go", "untracked.go"} {
		if _, err := os.Stat(e.Store.ShardPathFor(rel)); err != nil {
			t.Errorf("缺分片:%s", rel)
		}
	}
	for _, rel := range []string{"vendor/dep/dep.go", "internal/auth/testdata/f.go", "gen.go", "ignored.go"} {
		if _, err := os.Stat(e.Store.ShardPathFor(rel)); !os.IsNotExist(err) {
			t.Errorf("不应索引:%s", rel)
		}
	}

	// 幂等:重复 init 零变化、分片字节不变。
	shardPath := e.Store.ShardPathFor("internal/auth/login.go")
	before, _ := os.ReadFile(shardPath)
	_, rep2 := initRepo(t, repo, engine.InitOptions{})
	if rep2.Created != 0 || rep2.Suspected != 0 || rep2.Migrated != 0 || rep2.Orphaned != 0 {
		t.Errorf("重复 init 应零变化:%s", rep2.Text())
	}
	after, _ := os.ReadFile(shardPath)
	if string(before) != string(after) {
		t.Error("重复 init 改变了分片")
	}

	// 消化 Login,然后改名 → StructHash 精确迁移,知识与血缘无损(附录 E)。
	sh, raw, err := e.Store.LoadShard(shardPath)
	if err != nil {
		t.Fatal(err)
	}
	for i := range sh.Nodes {
		if sh.Nodes[i].ID == "internal/auth/login.go#Login" {
			sh.Nodes[i].Entries = []model.Entry{{
				ID: model.NewEntryID(), Kind: model.KindPitfall,
				Text: "不要在调用方预先加密", Confidence: model.ConfidenceInferred,
			}}
			sh.Nodes[i].Status = model.StatusFresh
		}
	}
	if err := e.Store.SaveShard(shardPath, sh, raw); err != nil {
		t.Fatal(err)
	}

	renamed := strings.ReplaceAll(fixture["internal/auth/login.go"], "Login", "Authenticate")
	if err := os.WriteFile(filepath.Join(repo, "internal/auth/login.go"), []byte(renamed), 0o644); err != nil {
		t.Fatal(err)
	}
	_, rep3 := initRepo(t, repo, engine.InitOptions{})
	if rep3.Migrated != 1 {
		t.Fatalf("改名应精确迁移:%s", rep3.Text())
	}
	sh2, _, err := e.Store.LoadShard(shardPath)
	if err != nil {
		t.Fatal(err)
	}
	var migrated *model.Node
	for i := range sh2.Nodes {
		if sh2.Nodes[i].ID == "internal/auth/login.go#Authenticate" {
			migrated = &sh2.Nodes[i]
		}
		if sh2.Nodes[i].ID == "internal/auth/login.go#Login" {
			t.Error("旧 ID 节点应消失")
		}
	}
	if migrated == nil {
		t.Fatal("迁移目标节点不存在")
	}
	if len(migrated.Entries) != 1 || migrated.Entries[0].Text != "不要在调用方预先加密" {
		t.Errorf("知识未随迁移带走:%+v", migrated.Entries)
	}
	if len(migrated.Lineage) != 1 || migrated.Lineage[0] != "internal/auth/login.go#Login" {
		t.Errorf("血缘未接续:%v", migrated.Lineage)
	}
	if migrated.Status != model.StatusFresh {
		t.Errorf("迁移后状态 = %s, want fresh", migrated.Status)
	}
}

// TestE2ENoGit 无 git 仓库走 WalkDir 回退(impl §1 非 git 可用定案)。
func TestE2ENoGit(t *testing.T) {
	repo := t.TempDir()
	for rel, content := range fixture {
		p := filepath.Join(repo, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	e, rep := initRepo(t, repo, engine.InitOptions{})
	if rep.Files != 2 { // main.go + login.go(排除项同 git 路径)
		t.Errorf("Files = %d, want 2(%s)", rep.Files, rep.Text())
	}
	if _, err := os.Stat(e.Store.ShardPathFor("internal/auth/login.go")); err != nil {
		t.Error("无 git 回退未生成分片")
	}
}

// TestCLIRunInit CLI 出口:退出码、报告输出、.mcp.json 片段、写者锁。
func TestCLIRunInit(t *testing.T) {
	repo := t.TempDir()
	if err := os.WriteFile(filepath.Join(repo, "a.go"), []byte("package p\n\nfunc A() {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if code := run([]string{"init", "--repo", repo}); code != 0 {
		t.Fatalf("init 退出码 = %d", code)
	}
	if _, err := os.Stat(filepath.Join(repo, ".knowledge", "project.yaml")); err != nil {
		t.Error("CLI init 未建库")
	}
	// serve 被 flock 挡:模拟 serve 持锁时 CLI init 报错。
	s, _ := store.Open(repo)
	release, err := s.AcquireWriterLock()
	if err != nil {
		t.Fatal(err)
	}
	defer release()
	if code := run([]string{"init", "--repo", repo}); code == 0 {
		t.Error("持锁期间 init 应失败(serve 运行中)")
	}
}

func TestCLIUnknownCommand(t *testing.T) {
	if code := run([]string{"bogus"}); code == 0 {
		t.Error("未知子命令应非零退出")
	}
	if code := run([]string{"serve"}); code == 0 {
		t.Error("serve 未实现应非零退出")
	}
}
